"""Recommended preset: the settings the hosted service runs, on one machine.

It needs an OpenRouter key for the tagging and summarization model and the
``proxy`` and ``embeddings`` extras. Storage is SQLite, and the optional
parts (PostgreSQL vector search, the judgment layer, group attribution) stay
off; each is one section of docs/configuration.md away.
"""

from __future__ import annotations

import yaml

from .base import Preset, register_preset


RECOMMENDED_TEMPLATE = """\
# virtual-context configuration: recommended preset
# Generated by: virtual-context init recommended
# Docs: https://github.com/virtual-context/virtual-context/blob/main/docs/configuration.md
#
# Needs: pip install "virtual-context[proxy,embeddings]" and OPENROUTER_API_KEY.

version: "0.2"
storage_root: ".virtualcontext"
context_window: 200000
token_counter: "tiktoken"

paging:
  enabled: true

tag_generator:
  type: "llm"
  provider: "openrouter"
  model: "google/gemini-2.5-flash-lite"
  max_tags: 10
  min_tags: 5
  max_tokens: 8192
  prompt_mode: "detailed"
  context_lookback_pairs: 5
  context_bleed_threshold: 0.1
  temporal_heuristic_enabled: true
  tag_splitting:
    enabled: false

summarization:
  provider: "openrouter"
  model: "google/gemini-2.5-flash-lite"
  max_tokens: 1000
  temperature: 0.3

providers:
  openrouter:
    type: "openrouter"
    base_url: "https://openrouter.ai/api/v1"
    api_key_env: "OPENROUTER_API_KEY"

storage:
  backend: "sqlite"

compaction:
  soft_threshold: 0.70
  hard_threshold: 0.85
  protected_recent_turns: 6
  defer_payload_mutation: true
  flush_ttl_seconds: 300
  fill_pass_enabled: false
  overflow_buffer: 1.2
  summary_ratio: 0.15
  min_summary_tokens: 200
  max_summary_tokens: 2000
  max_concurrent_summaries: 4
  llm_token_overhead: 2000
  session_gap_minutes: 720
  tag_overlap_threshold: 0.5
  max_segment_turns: 20
  tool_result_segment_threshold: 50000

tool_output:
  enabled: true
  default_truncate_threshold: 8192

assembly:
  core_context_max_tokens: 18000
  tag_context_max_tokens: 30000
  facts_max_tokens: 20000
  recent_turns_always_included: 3
  context_hint_enabled: true
  context_hint_max_tokens: 2000

retrieval:
  skip_active_tags: true
  active_tag_lookback: 4
  anchorless_lookback: 6
  inbound_tagger_type: "embedding"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_threshold: 0.3
  fact_dense_retrieval: true
  fact_dense_top_n: 20
  scoring:
    embedding_context_turns: 2
    embedding_context_guard: true

# Keep only the retrieved facts relevant to the question (uses the summarization model).
curation:
  enabled: true

facts:
  graph_links: true

telemetry:
  enabled: true
"""

RECOMMENDED_CONFIG: dict = yaml.safe_load(RECOMMENDED_TEMPLATE)

register_preset(Preset(
    name="recommended",
    description="The hosted service's settings on one machine (OpenRouter + SQLite)",
    config_dict=RECOMMENDED_CONFIG,
    template=RECOMMENDED_TEMPLATE,
    next_steps=[
        'Install the extras:  pip install "virtual-context[proxy,embeddings]"',
        "Set your key:        export OPENROUTER_API_KEY=...",
        "Validate:            virtual-context config validate",
        "Start the proxy:     virtual-context proxy --upstream https://api.anthropic.com",
    ],
))
