"""Recommended presets: the settings the hosted service runs, on one machine.

``recommended`` calls the tagging and summarization model through
OpenRouter; ``recommended-local`` calls a model on a local OpenAI-compatible
server (Ollama, LM Studio, llama.cpp, vLLM). Everything else is identical:
SQLite storage, paging tools on, fact curation and dense fact retrieval on.
Both need the ``proxy`` and ``embeddings`` extras. The optional parts
(PostgreSQL vector search, the judgment layer, group attribution) stay off.
"""

from __future__ import annotations

import yaml

from .base import Preset, register_preset

# The one part that differs: where the tagging and summarization model runs.
# Any model the endpoint serves works; the named one is only a starting point.
_MODEL_SECTION = """\
# The model that tags turns and writes summaries. Swap in any model the
# endpoint serves; quality depends on the model you choose.
tag_generator:
  type: "llm"
  provider: "{provider}"
  model: "{model}"
  max_tags: 10
  min_tags: 5
  max_tokens: 8192
  prompt_mode: "detailed"
  context_lookback_pairs: 5
  context_bleed_threshold: 0.1
  temporal_heuristic_enabled: true
  tag_splitting:
    enabled: false

summarization:
  provider: "{provider}"
  model: "{model}"
  max_tokens: 1000
  temperature: 0.3

{providers}
"""

_HOSTED_PROVIDERS = """\
providers:
  openrouter:
    type: "openrouter"
    base_url: "https://openrouter.ai/api/v1"
    api_key_env: "OPENROUTER_API_KEY"
"""

_LOCAL_PROVIDERS = """\
providers:
  local:
    # Any OpenAI-compatible server: Ollama (below), LM Studio, llama.cpp, vLLM.
    type: "generic_openai"
    base_url: "http://127.0.0.1:11434/v1"
"""

_HEAD = """\
# virtual-context configuration: {name} preset
# Generated by: virtual-context init {name}
# Docs: https://github.com/virtual-context/virtual-context/blob/main/docs/configuration.md
#
# Needs: pip install "virtual-context[proxy,embeddings]" and {needs}.

version: "0.2"
storage_root: ".virtualcontext"
context_window: 200000
token_counter: "tiktoken"

paging:
  enabled: true

"""

_TAIL = """\
storage:
  backend: "sqlite"

compaction:
  soft_threshold: 0.70
  hard_threshold: 0.85
  protected_recent_turns: 6
  defer_payload_mutation: true
  flush_ttl_seconds: 300
  fill_pass_enabled: false
  overflow_buffer: 1.2
  summary_ratio: 0.15
  min_summary_tokens: 200
  max_summary_tokens: 2000
  max_concurrent_summaries: 4
  llm_token_overhead: 2000
  session_gap_minutes: 720
  tag_overlap_threshold: 0.5
  max_segment_turns: 20
  tool_result_segment_threshold: 50000

tool_output:
  enabled: true
  default_truncate_threshold: 8192

assembly:
  core_context_max_tokens: 18000
  tag_context_max_tokens: 30000
  facts_max_tokens: 20000
  recent_turns_always_included: 3
  context_hint_enabled: true
  context_hint_max_tokens: 2000

retrieval:
  skip_active_tags: true
  active_tag_lookback: 4
  anchorless_lookback: 6
  inbound_tagger_type: "embedding"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_threshold: 0.3
  fact_dense_retrieval: true
  fact_dense_top_n: 20
  scoring:
    embedding_context_turns: 2
    embedding_context_guard: true

# Keep only the retrieved facts relevant to the question (uses the summarization model).
curation:
  enabled: true

facts:
  graph_links: true

telemetry:
  enabled: true
"""


def _template(name: str, needs: str, provider: str, model: str, providers: str) -> str:
    return (
        _HEAD.format(name=name, needs=needs)
        + _MODEL_SECTION.format(provider=provider, model=model, providers=providers)
        + _TAIL
    )


RECOMMENDED_TEMPLATE = _template(
    "recommended", "OPENROUTER_API_KEY", "openrouter", "google/gemini-2.5-flash-lite", _HOSTED_PROVIDERS,
)
RECOMMENDED_LOCAL_TEMPLATE = _template(
    "recommended-local", "a local OpenAI-compatible model server", "local", "qwen3:4b-instruct-2507-q4_K_M", _LOCAL_PROVIDERS,
)

register_preset(Preset(
    name="recommended",
    description="Production settings on one machine; tagging and summaries through OpenRouter",
    config_dict=yaml.safe_load(RECOMMENDED_TEMPLATE),
    template=RECOMMENDED_TEMPLATE,
    next_steps=[
        'Install the extras:  pip install "virtual-context[proxy,embeddings]"',
        "Set your key:        export OPENROUTER_API_KEY=...",
        "Pick a model:        edit tag_generator.model and summarization.model (any OpenRouter model)",
        "Start the proxy:     virtual-context proxy --upstream https://api.anthropic.com",
    ],
))

register_preset(Preset(
    name="recommended-local",
    description="Production settings on one machine; tagging and summaries on a local model server",
    config_dict=yaml.safe_load(RECOMMENDED_LOCAL_TEMPLATE),
    template=RECOMMENDED_LOCAL_TEMPLATE,
    next_steps=[
        'Install the extras:  pip install "virtual-context[proxy,embeddings]"',
        "Start a model server with the model named in the file, e.g.: ollama pull qwen3:4b-instruct-2507-q4_K_M",
        "Pick a model:        edit tag_generator.model and summarization.model (any model the server serves)",
        "Start the proxy:     virtual-context proxy --upstream https://api.anthropic.com",
    ],
))
